# Form implementation generated from reading ui file 'D:\ProjectTotNghiep\MainUI.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1212, 831)
        MainWindow.setMinimumSize(QtCore.QSize(1212, 831))
        MainWindow.setMaximumSize(QtCore.QSize(1212, 831))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, -10, 1211, 818))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.icon_only_widget = QtWidgets.QWidget(parent=self.layoutWidget)
        self.icon_only_widget.setEnabled(True)
        self.icon_only_widget.setMinimumSize(QtCore.QSize(71, 0))
        self.icon_only_widget.setMaximumSize(QtCore.QSize(71, 800))
        self.icon_only_widget.setStyleSheet("QWidget{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color:white;\n"
"border-radius:3px;\n"
"}")
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_4 = QtWidgets.QLabel(parent=self.icon_only_widget)
        self.label_4.setMaximumSize(QtCore.QSize(40, 40))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/logo.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_12.addWidget(self.label_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 25, -1, -1)
        self.verticalLayout_5.setSpacing(20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.dashboard_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.dashboard_1.setMinimumSize(QtCore.QSize(0, 28))
        self.dashboard_1.setStyleSheet("")
        self.dashboard_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/dashboardsmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(":/dashboardsmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.dashboard_1.setIcon(icon)
        self.dashboard_1.setIconSize(QtCore.QSize(100, 19))
        self.dashboard_1.setCheckable(True)
        self.dashboard_1.setObjectName("dashboard_1")
        self.verticalLayout_5.addWidget(self.dashboard_1)
        self.institution_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.institution_1.setMinimumSize(QtCore.QSize(0, 28))
        self.institution_1.setStyleSheet("")
        self.institution_1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/institutionsmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap(":/institutionsmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.institution_1.setIcon(icon1)
        self.institution_1.setIconSize(QtCore.QSize(100, 18))
        self.institution_1.setCheckable(True)
        self.institution_1.setObjectName("institution_1")
        self.verticalLayout_5.addWidget(self.institution_1)
        self.students_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.students_1.setStyleSheet("")
        self.students_1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/studentssmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap(":/studentssmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.students_1.setIcon(icon2)
        self.students_1.setIconSize(QtCore.QSize(100, 20))
        self.students_1.setCheckable(True)
        self.students_1.setObjectName("students_1")
        self.verticalLayout_5.addWidget(self.students_1)
        self.teachers_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.teachers_1.setStyleSheet("")
        self.teachers_1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/teacherssmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3.addPixmap(QtGui.QPixmap(":/teacherssmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.teachers_1.setIcon(icon3)
        self.teachers_1.setIconSize(QtCore.QSize(100, 20))
        self.teachers_1.setCheckable(True)
        self.teachers_1.setObjectName("teachers_1")
        self.verticalLayout_5.addWidget(self.teachers_1)
        self.finances_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.finances_1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/financessmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon4.addPixmap(QtGui.QPixmap(":/financessmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.finances_1.setIcon(icon4)
        self.finances_1.setIconSize(QtCore.QSize(100, 20))
        self.finances_1.setCheckable(True)
        self.finances_1.setObjectName("finances_1")
        self.verticalLayout_5.addWidget(self.finances_1)
        self.verticalLayout_12.addLayout(self.verticalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(20, 378, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_12.addItem(spacerItem)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(15)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.settings_2 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.settings_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/settingssmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon5.addPixmap(QtGui.QPixmap(":/settingssmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.settings_2.setIcon(icon5)
        self.settings_2.setIconSize(QtCore.QSize(100, 20))
        self.settings_2.setCheckable(True)
        self.settings_2.setObjectName("settings_2")
        self.verticalLayout_11.addWidget(self.settings_2)
        self.sign_out_2 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.sign_out_2.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/signoutsmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon6.addPixmap(QtGui.QPixmap(":/signoutsmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.sign_out_2.setIcon(icon6)
        self.sign_out_2.setIconSize(QtCore.QSize(100, 20))
        self.sign_out_2.setCheckable(True)
        self.sign_out_2.setObjectName("sign_out_2")
        self.verticalLayout_11.addWidget(self.sign_out_2)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)
        self.icon_text_widget = QtWidgets.QWidget(parent=self.layoutWidget)
        self.icon_text_widget.setMaximumSize(QtCore.QSize(16777215, 800))
        self.icon_text_widget.setStyleSheet("QWidget{\n"
"background-color: rgb(0, 0, 0);\n"
"color:white;\n"
"}\n"
"QPushButton{\n"
"height:30px;\n"
"border:none;\n"
"\n"
"}")
        self.icon_text_widget.setObjectName("icon_text_widget")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.icon_text_widget)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_2 = QtWidgets.QLabel(parent=self.icon_text_widget)
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_13.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.icon_text_widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_13.addWidget(self.label_3)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.dashboard_2 = QtWidgets.QPushButton(parent=self.icon_text_widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dashboard_2.setFont(font)
        self.dashboard_2.setStyleSheet("QPushButton{\n"
"padding-left:-60px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color:white;\n"
"border-radius:3px;\n"
"}")
        self.dashboard_2.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/dashboard2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon7.addPixmap(QtGui.QPixmap(":/dashboard1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.dashboard_2.setIcon(icon7)
        self.dashboard_2.setIconSize(QtCore.QSize(100, 60))
        self.dashboard_2.setCheckable(True)
        self.dashboard_2.setObjectName("dashboard_2")
        self.verticalLayout_10.addWidget(self.dashboard_2)
        self.institution_2 = QtWidgets.QPushButton(parent=self.icon_text_widget)
        self.institution_2.setStyleSheet("QPushButton{\n"
"padding-left:-65px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color:white;\n"
"border-radius:3px;\n"
"}")
        self.institution_2.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/institution2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon8.addPixmap(QtGui.QPixmap(":/institution1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.institution_2.setIcon(icon8)
        self.institution_2.setIconSize(QtCore.QSize(95, 45))
        self.institution_2.setCheckable(True)
        self.institution_2.setObjectName("institution_2")
        self.verticalLayout_10.addWidget(self.institution_2)
        self.students = QtWidgets.QFrame(parent=self.icon_text_widget)
        self.students.setEnabled(True)
        self.students.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.students.setObjectName("students")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.students)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.students_2 = QtWidgets.QPushButton(parent=self.students)
        self.students_2.setMinimumSize(QtCore.QSize(204, 30))
        self.students_2.setStyleSheet("QPushButton:checked{\n"
"\n"
"    borde-radius:3px;\n"
"}")
        self.students_2.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/students3.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon9.addPixmap(QtGui.QPixmap(":/students4.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.students_2.setIcon(icon9)
        self.students_2.setIconSize(QtCore.QSize(200, 60))
        self.students_2.setCheckable(True)
        self.students_2.setObjectName("students_2")
        self.verticalLayout_7.addWidget(self.students_2)
        self.students_dropdown = QtWidgets.QFrame(parent=self.students)
        self.students_dropdown.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.students_dropdown.setObjectName("students_dropdown")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.students_dropdown)
        self.verticalLayout_14.setSpacing(5)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.student_info = QtWidgets.QPushButton(parent=self.students_dropdown)
        self.student_info.setStyleSheet("QPushButton{\n"
"padding-left:45px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.student_info.setCheckable(True)
        self.student_info.setObjectName("student_info")
        self.verticalLayout_14.addWidget(self.student_info)
        self.student_payments = QtWidgets.QPushButton(parent=self.students_dropdown)
        self.student_payments.setStyleSheet("QPushButton{\n"
"padding-left:35px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.student_payments.setCheckable(True)
        self.student_payments.setObjectName("student_payments")
        self.verticalLayout_14.addWidget(self.student_payments)
        self.student_transactions = QtWidgets.QPushButton(parent=self.students_dropdown)
        self.student_transactions.setStyleSheet("QPushButton{\n"
"padding-left:50px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.student_transactions.setCheckable(True)
        self.student_transactions.setObjectName("student_transactions")
        self.verticalLayout_14.addWidget(self.student_transactions)
        self.verticalLayout_7.addWidget(self.students_dropdown)
        self.verticalLayout_10.addWidget(self.students)
        self.teachers = QtWidgets.QFrame(parent=self.icon_text_widget)
        self.teachers.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.teachers.setObjectName("teachers")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.teachers)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.teachers_2 = QtWidgets.QPushButton(parent=self.teachers)
        self.teachers_2.setMinimumSize(QtCore.QSize(204, 30))
        self.teachers_2.setStyleSheet("QPushButton:checked{\n"
"    \n"
"    borde-radius:3px;\n"
"}")
        self.teachers_2.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/teachers3.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon10.addPixmap(QtGui.QPixmap(":/teachers4.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.teachers_2.setIcon(icon10)
        self.teachers_2.setIconSize(QtCore.QSize(200, 60))
        self.teachers_2.setCheckable(True)
        self.teachers_2.setObjectName("teachers_2")
        self.verticalLayout_6.addWidget(self.teachers_2)
        self.teachers_dropdown = QtWidgets.QFrame(parent=self.teachers)
        self.teachers_dropdown.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.teachers_dropdown.setObjectName("teachers_dropdown")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.teachers_dropdown)
        self.verticalLayout_15.setSpacing(5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.teacher_info = QtWidgets.QPushButton(parent=self.teachers_dropdown)
        self.teacher_info.setStyleSheet("QPushButton{\n"
"padding-left:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.teacher_info.setCheckable(True)
        self.teacher_info.setObjectName("teacher_info")
        self.verticalLayout_15.addWidget(self.teacher_info)
        self.teacher_salaries = QtWidgets.QPushButton(parent=self.teachers_dropdown)
        self.teacher_salaries.setStyleSheet("QPushButton{\n"
"padding-left:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.teacher_salaries.setCheckable(True)
        self.teacher_salaries.setObjectName("teacher_salaries")
        self.verticalLayout_15.addWidget(self.teacher_salaries)
        self.teacher_transactions = QtWidgets.QPushButton(parent=self.teachers_dropdown)
        self.teacher_transactions.setStyleSheet("QPushButton{\n"
"padding-left:28px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.teacher_transactions.setCheckable(True)
        self.teacher_transactions.setObjectName("teacher_transactions")
        self.verticalLayout_15.addWidget(self.teacher_transactions)
        self.verticalLayout_6.addWidget(self.teachers_dropdown)
        self.verticalLayout_10.addWidget(self.teachers)
        self.finances = QtWidgets.QFrame(parent=self.icon_text_widget)
        self.finances.setEnabled(True)
        self.finances.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.finances.setObjectName("finances")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.finances)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.finances_2 = QtWidgets.QPushButton(parent=self.finances)
        self.finances_2.setMinimumSize(QtCore.QSize(204, 30))
        self.finances_2.setStyleSheet("QPushButton:checked{\n"
"\n"
"    borde-radius:3px;\n"
"}")
        self.finances_2.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/finances3.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon11.addPixmap(QtGui.QPixmap(":/finances4.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.finances_2.setIcon(icon11)
        self.finances_2.setIconSize(QtCore.QSize(200, 100))
        self.finances_2.setCheckable(True)
        self.finances_2.setObjectName("finances_2")
        self.verticalLayout_8.addWidget(self.finances_2)
        self.finances_dropdown = QtWidgets.QFrame(parent=self.finances)
        self.finances_dropdown.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.finances_dropdown.setObjectName("finances_dropdown")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.finances_dropdown)
        self.verticalLayout_16.setSpacing(5)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.budgets = QtWidgets.QPushButton(parent=self.finances_dropdown)
        self.budgets.setStyleSheet("QPushButton{\n"
"padding-left:-27px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.budgets.setCheckable(True)
        self.budgets.setObjectName("budgets")
        self.verticalLayout_16.addWidget(self.budgets)
        self.expenses = QtWidgets.QPushButton(parent=self.finances_dropdown)
        self.expenses.setStyleSheet("QPushButton{\n"
"padding-left:-19px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.expenses.setCheckable(True)
        self.expenses.setObjectName("expenses")
        self.verticalLayout_16.addWidget(self.expenses)
        self.business_overview = QtWidgets.QPushButton(parent=self.finances_dropdown)
        self.business_overview.setStyleSheet("QPushButton{\n"
"padding-left:32px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.business_overview.setCheckable(True)
        self.business_overview.setObjectName("business_overview")
        self.verticalLayout_16.addWidget(self.business_overview)
        self.verticalLayout_8.addWidget(self.finances_dropdown)
        self.verticalLayout_10.addWidget(self.finances)
        self.verticalLayout_13.addLayout(self.verticalLayout_10)
        spacerItem1 = QtWidgets.QSpacerItem(20, 289, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_13.addItem(spacerItem1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(15)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.settings_1 = QtWidgets.QPushButton(parent=self.icon_text_widget)
        self.settings_1.setStyleSheet("QPushButton{\n"
"padding-left:-65px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color:white;\n"
"    border-radius:3px;\n"
"}")
        self.settings_1.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/settings2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon12.addPixmap(QtGui.QPixmap(":/settings1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.settings_1.setIcon(icon12)
        self.settings_1.setIconSize(QtCore.QSize(100, 60))
        self.settings_1.setCheckable(True)
        self.settings_1.setObjectName("settings_1")
        self.verticalLayout_9.addWidget(self.settings_1)
        self.sign_out_1 = QtWidgets.QPushButton(parent=self.icon_text_widget)
        self.sign_out_1.setStyleSheet("QPushButton{\n"
"padding-left:-65px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color:white;\n"
"    border-radius:3px;\n"
"}")
        self.sign_out_1.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/signout2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon13.addPixmap(QtGui.QPixmap(":/signout1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.sign_out_1.setIcon(icon13)
        self.sign_out_1.setIconSize(QtCore.QSize(100, 60))
        self.sign_out_1.setCheckable(True)
        self.sign_out_1.setObjectName("sign_out_1")
        self.verticalLayout_9.addWidget(self.sign_out_1)
        self.verticalLayout_13.addLayout(self.verticalLayout_9)
        self.label_2.raise_()
        self.label_3.raise_()
        self.gridLayout.addWidget(self.icon_text_widget, 0, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.qwww = QtWidgets.QWidget(parent=self.layoutWidget)
        self.qwww.setEnabled(True)
        self.qwww.setObjectName("qwww")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.qwww)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menu_items = QtWidgets.QPushButton(parent=self.qwww)
        self.menu_items.setStyleSheet("border:none;")
        self.menu_items.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/menu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menu_items.setIcon(icon14)
        self.menu_items.setIconSize(QtCore.QSize(29, 35))
        self.menu_items.setCheckable(True)
        self.menu_items.setObjectName("menu_items")
        self.horizontalLayout_2.addWidget(self.menu_items)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.qwww)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_5 = QtWidgets.QLabel(parent=self.qwww)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(72, 72, 72);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.qwww)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 31))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"padding-left:20px;\n"
"border:1px solid gray;\n"
"border-radius:10px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label_6 = QtWidgets.QLabel(parent=self.qwww)
        self.label_6.setMaximumSize(QtCore.QSize(40, 40))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/profile.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.qwww)
        self.main_screen_widget = QtWidgets.QWidget(parent=self.layoutWidget)
        self.main_screen_widget.setEnabled(True)
        self.main_screen_widget.setMinimumSize(QtCore.QSize(841, 741))
        self.main_screen_widget.setMaximumSize(QtCore.QSize(841, 800))
        self.main_screen_widget.setStyleSheet("")
        self.main_screen_widget.setObjectName("main_screen_widget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.main_screen_widget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 841, 701))
        self.stackedWidget.setMaximumSize(QtCore.QSize(841, 741))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_7 = QtWidgets.QLabel(parent=self.page)
        self.label_7.setGeometry(QtCore.QRect(320, 240, 221, 141))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_8 = QtWidgets.QLabel(parent=self.page_2)
        self.label_8.setGeometry(QtCore.QRect(340, 200, 161, 141))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_9 = QtWidgets.QLabel(parent=self.page_3)
        self.label_9.setGeometry(QtCore.QRect(20, 0, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_18 = QtWidgets.QLabel(parent=self.page_3)
        self.label_18.setGeometry(QtCore.QRect(20, 40, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.customerInfo_table = QtWidgets.QTableWidget(parent=self.page_3)
        self.customerInfo_table.setGeometry(QtCore.QRect(20, 200, 821, 511))
        self.customerInfo_table.setStyleSheet("QHeaderView::section{\n"
" font-weight:bold;\n"
" background-color:black;\n"
"color:white;\n"
"}\n"
"\n"
"QTableWidget{\n"
" alternate-background-color: #B0EDFB;\n"
" background-color: #F4F9FA;\n"
"}\n"
"")
        self.customerInfo_table.setAlternatingRowColors(True)
        self.customerInfo_table.setObjectName("customerInfo_table")
        self.customerInfo_table.setColumnCount(9)
        self.customerInfo_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.customerInfo_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.customerInfo_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.customerInfo_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.customerInfo_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.customerInfo_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.customerInfo_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.customerInfo_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.customerInfo_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.customerInfo_table.setHorizontalHeaderItem(8, item)
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.page_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 90, 441, 43))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.addCustomer_btn = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.addCustomer_btn.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.addCustomer_btn.setFont(font)
        self.addCustomer_btn.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"\n"
"}")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/add student.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.addCustomer_btn.setIcon(icon15)
        self.addCustomer_btn.setObjectName("addCustomer_btn")
        self.horizontalLayout_4.addWidget(self.addCustomer_btn)
        self.excelExport_btn = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.excelExport_btn.setEnabled(True)
        self.excelExport_btn.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.excelExport_btn.setFont(font)
        self.excelExport_btn.setStyleSheet("QPushButton{\n"
"    background-color: #34D481;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"\n"
"}")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/excel.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.excelExport_btn.setIcon(icon16)
        self.excelExport_btn.setObjectName("excelExport_btn")
        self.horizontalLayout_4.addWidget(self.excelExport_btn)
        self.pdfExport_btn = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.pdfExport_btn.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.pdfExport_btn.setFont(font)
        self.pdfExport_btn.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(255, 78, 78);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"\n"
"}")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/pdf.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pdfExport_btn.setIcon(icon17)
        self.pdfExport_btn.setObjectName("pdfExport_btn")
        self.horizontalLayout_4.addWidget(self.pdfExport_btn)
        self.layoutWidget2 = QtWidgets.QWidget(parent=self.page_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 150, 581, 43))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.select_gender = QtWidgets.QComboBox(parent=self.layoutWidget2)
        self.select_gender.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(9)
        font.setBold(False)
        self.select_gender.setFont(font)
        self.select_gender.setStyleSheet("QComboBox{\n"
"    border: 2px solid white;\n"
"    border-radius: 8px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    background-color: black;\n"
"    color: white;\n"
"    height: 35px;\n"
"    padding-left: 15px;\n"
"    font-weight: ;\n"
"    selection-background-color: #2980B9;\n"
"}\n"
"")
        self.select_gender.setObjectName("select_gender")
        self.select_gender.addItem("")
        self.select_gender.addItem("")
        self.select_gender.addItem("")
        self.select_gender.addItem("")
        self.horizontalLayout_5.addWidget(self.select_gender)
        self.select_model = QtWidgets.QComboBox(parent=self.layoutWidget2)
        self.select_model.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(9)
        font.setBold(False)
        self.select_model.setFont(font)
        self.select_model.setStyleSheet("QComboBox{\n"
"    border: 2px solid white;\n"
"    border-radius: 8px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    background-color: black;\n"
"    color: white;\n"
"    height: 35px;\n"
"    padding-left: 15px;\n"
"    font-weight: ;\n"
"    selection-background-color: #2980B9;\n"
"}\n"
"")
        self.select_model.setObjectName("select_model")
        self.select_model.addItem("")
        self.select_model.addItem("")
        self.select_model.addItem("")
        self.select_model.addItem("")
        self.select_model.addItem("")
        self.select_model.addItem("")
        self.select_model.addItem("")
        self.select_model.addItem("")
        self.select_model.addItem("")
        self.select_model.addItem("")
        self.select_model.addItem("")
        self.horizontalLayout_5.addWidget(self.select_model)
        self.search_student = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        self.search_student.setMinimumSize(QtCore.QSize(0, 31))
        self.search_student.setStyleSheet("QLineEdit{\n"
"padding-left:20px;\n"
"border:1px solid gray;\n"
"border-radius:10px;\n"
"}")
        self.search_student.setObjectName("search_student")
        self.horizontalLayout_5.addWidget(self.search_student)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_10 = QtWidgets.QLabel(parent=self.page_4)
        self.label_10.setGeometry(QtCore.QRect(270, 200, 301, 141))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_11 = QtWidgets.QLabel(parent=self.page_5)
        self.label_11.setGeometry(QtCore.QRect(250, 200, 361, 141))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_12 = QtWidgets.QLabel(parent=self.page_6)
        self.label_12.setGeometry(QtCore.QRect(290, 230, 271, 141))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.label_13 = QtWidgets.QLabel(parent=self.page_7)
        self.label_13.setGeometry(QtCore.QRect(310, 200, 221, 141))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.label_14 = QtWidgets.QLabel(parent=self.page_8)
        self.label_14.setGeometry(QtCore.QRect(280, 210, 281, 141))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.stackedWidget.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.label_15 = QtWidgets.QLabel(parent=self.page_9)
        self.label_15.setGeometry(QtCore.QRect(350, 210, 181, 141))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.stackedWidget.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.label_16 = QtWidgets.QLabel(parent=self.page_10)
        self.label_16.setGeometry(QtCore.QRect(350, 210, 161, 141))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.stackedWidget.addWidget(self.page_10)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.label_17 = QtWidgets.QLabel(parent=self.page_11)
        self.label_17.setGeometry(QtCore.QRect(280, 190, 311, 141))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.stackedWidget.addWidget(self.page_11)
        self.verticalLayout_4.addWidget(self.main_screen_widget)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(8)
        self.students_2.toggled['bool'].connect(self.students_dropdown.setHidden) # type: ignore
        self.teachers_2.toggled['bool'].connect(self.teachers_dropdown.setHidden) # type: ignore
        self.finances_2.toggled['bool'].connect(self.finances_dropdown.setHidden) # type: ignore
        self.dashboard_2.toggled['bool'].connect(self.dashboard_1.setChecked) # type: ignore
        self.institution_2.toggled['bool'].connect(self.institution_1.setChecked) # type: ignore
        self.students_2.toggled['bool'].connect(self.students_1.setChecked) # type: ignore
        self.teachers_2.toggled['bool'].connect(self.teachers_1.setChecked) # type: ignore
        self.finances_2.toggled['bool'].connect(self.finances_1.setChecked) # type: ignore
        self.settings_1.toggled['bool'].connect(self.settings_2.setChecked) # type: ignore
        self.sign_out_1.toggled['bool'].connect(self.sign_out_2.setChecked) # type: ignore
        self.sign_out_2.toggled['bool'].connect(MainWindow.close) # type: ignore
        self.sign_out_1.toggled['bool'].connect(MainWindow.close) # type: ignore
        self.menu_items.toggled['bool'].connect(self.icon_text_widget.setHidden) # type: ignore
        self.menu_items.toggled['bool'].connect(self.icon_only_widget.setVisible) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.student_info.setText(_translate("MainWindow", "Customer Information"))
        self.student_payments.setText(_translate("MainWindow", "Customer Payments"))
        self.student_transactions.setText(_translate("MainWindow", "Customer Transactions"))
        self.teacher_info.setText(_translate("MainWindow", "Staff Information"))
        self.teacher_salaries.setText(_translate("MainWindow", "Staff Salaries"))
        self.teacher_transactions.setText(_translate("MainWindow", "Staff Transactions"))
        self.budgets.setText(_translate("MainWindow", "Budgets"))
        self.expenses.setText(_translate("MainWindow", "Expenses"))
        self.business_overview.setText(_translate("MainWindow", "Business Overview"))
        self.label.setText(_translate("MainWindow", "Hello"))
        self.label_5.setText(_translate("MainWindow", "Welcome to your page"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search Here..."))
        self.label_7.setText(_translate("MainWindow", "Dashboard"))
        self.label_8.setText(_translate("MainWindow", "Institution"))
        self.label_9.setText(_translate("MainWindow", "Customer Info"))
        self.label_18.setText(_translate("MainWindow", "Welcome to the customer information page"))
        item = self.customerInfo_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.customerInfo_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID"))
        item = self.customerInfo_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Gender"))
        item = self.customerInfo_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Birthday"))
        item = self.customerInfo_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Age"))
        item = self.customerInfo_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Address"))
        item = self.customerInfo_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Phone"))
        item = self.customerInfo_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Email"))
        item = self.customerInfo_table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Action"))
        self.addCustomer_btn.setText(_translate("MainWindow", "Add"))
        self.excelExport_btn.setText(_translate("MainWindow", "Export to Excel"))
        self.pdfExport_btn.setText(_translate("MainWindow", "Export to PDF"))
        self.select_gender.setItemText(0, _translate("MainWindow", "SELECT GENDER"))
        self.select_gender.setItemText(1, _translate("MainWindow", "Male"))
        self.select_gender.setItemText(2, _translate("MainWindow", "Female"))
        self.select_gender.setItemText(3, _translate("MainWindow", "Others"))
        self.select_model.setItemText(0, _translate("MainWindow", "SELECT MODEL"))
        self.select_model.setItemText(1, _translate("MainWindow", "Model 2"))
        self.select_model.setItemText(2, _translate("MainWindow", "Model 3"))
        self.select_model.setItemText(3, _translate("MainWindow", "Model 4"))
        self.select_model.setItemText(4, _translate("MainWindow", "Model 5"))
        self.select_model.setItemText(5, _translate("MainWindow", "Model 6"))
        self.select_model.setItemText(6, _translate("MainWindow", "Model 7"))
        self.select_model.setItemText(7, _translate("MainWindow", "Model 8"))
        self.select_model.setItemText(8, _translate("MainWindow", "Model 9"))
        self.select_model.setItemText(9, _translate("MainWindow", "Model 10"))
        self.select_model.setItemText(10, _translate("MainWindow", "Nam"))
        self.search_student.setPlaceholderText(_translate("MainWindow", "Search Customer..."))
        self.label_10.setText(_translate("MainWindow", "Customer Payments"))
        self.label_11.setText(_translate("MainWindow", "Customers Transactions"))
        self.label_12.setText(_translate("MainWindow", "Staff Information"))
        self.label_13.setText(_translate("MainWindow", "Staff Salaries"))
        self.label_14.setText(_translate("MainWindow", "Staff Transactions"))
        self.label_15.setText(_translate("MainWindow", "Budgets"))
        self.label_16.setText(_translate("MainWindow", "Expenses"))
        self.label_17.setText(_translate("MainWindow", "Bussiness Overview"))
