# Form implementation generated from reading ui file 'D:\ProjectTotNghiep\MainUI.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1212, 831)
        MainWindow.setMinimumSize(QtCore.QSize(1212, 831))
        MainWindow.setMaximumSize(QtCore.QSize(1212, 831))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(10, 0, 71, 831))
        self.widget.setMinimumSize(QtCore.QSize(71, 0))
        self.widget.setMaximumSize(QtCore.QSize(71, 16777215))
        self.widget.setStyleSheet("QWidget{\n"
"background-color: rgb(0, 0, 0);\n"
"}")
        self.widget.setObjectName("widget")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 40, 40))
        self.label_4.setMaximumSize(QtCore.QSize(40, 40))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/logo.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.layoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(-20, 80, 115, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.dashboard_1 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.dashboard_1.setStyleSheet("")
        self.dashboard_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/dashboardsmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(":/dashboardsmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.dashboard_1.setIcon(icon)
        self.dashboard_1.setIconSize(QtCore.QSize(16, 16))
        self.dashboard_1.setCheckable(True)
        self.dashboard_1.setObjectName("dashboard_1")
        self.verticalLayout_5.addWidget(self.dashboard_1)
        self.institution_1 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.institution_1.setStyleSheet("")
        self.institution_1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/institutionsmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap(":/institutionsmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.institution_1.setIcon(icon1)
        self.institution_1.setIconSize(QtCore.QSize(100, 16))
        self.institution_1.setCheckable(True)
        self.institution_1.setObjectName("institution_1")
        self.verticalLayout_5.addWidget(self.institution_1)
        self.students_2 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.students_2.setStyleSheet("")
        self.students_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/studentssmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap(":/studentssmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.students_2.setIcon(icon2)
        self.students_2.setIconSize(QtCore.QSize(100, 20))
        self.students_2.setCheckable(True)
        self.students_2.setObjectName("students_2")
        self.verticalLayout_5.addWidget(self.students_2)
        self.teachers_2 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.teachers_2.setStyleSheet("")
        self.teachers_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/teacherssmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3.addPixmap(QtGui.QPixmap(":/teacherssmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.teachers_2.setIcon(icon3)
        self.teachers_2.setIconSize(QtCore.QSize(100, 20))
        self.teachers_2.setCheckable(True)
        self.teachers_2.setObjectName("teachers_2")
        self.verticalLayout_5.addWidget(self.teachers_2)
        self.finances_2 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.finances_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/financessmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon4.addPixmap(QtGui.QPixmap(":/financessmall2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.finances_2.setIcon(icon4)
        self.finances_2.setIconSize(QtCore.QSize(100, 20))
        self.finances_2.setCheckable(True)
        self.finances_2.setObjectName("finances_2")
        self.verticalLayout_5.addWidget(self.finances_2)
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.widget)
        self.layoutWidget1.setGeometry(QtCore.QRect(-20, 716, 115, 81))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.settings_2 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.settings_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/settingssmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.settings_2.setIcon(icon5)
        self.settings_2.setIconSize(QtCore.QSize(100, 20))
        self.settings_2.setObjectName("settings_2")
        self.verticalLayout_11.addWidget(self.settings_2)
        self.sign_out_2 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.sign_out_2.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/signoutsmall1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.sign_out_2.setIcon(icon6)
        self.sign_out_2.setIconSize(QtCore.QSize(100, 20))
        self.sign_out_2.setObjectName("sign_out_2")
        self.verticalLayout_11.addWidget(self.sign_out_2)
        self.icon_text_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.icon_text_widget.setGeometry(QtCore.QRect(90, 0, 244, 831))
        self.icon_text_widget.setStyleSheet("QWidget{\n"
"background-color: rgb(0, 0, 0);\n"
"color:white;\n"
"}\n"
"QPushButton{\n"
"height:30px;\n"
"border:none;\n"
"\n"
"}")
        self.icon_text_widget.setObjectName("icon_text_widget")
        self.label_2 = QtWidgets.QLabel(parent=self.icon_text_widget)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 40, 40))
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.icon_text_widget)
        self.label_3.setGeometry(QtCore.QRect(130, 40, 47, 13))
        self.label_3.setObjectName("label_3")
        self.layoutWidget2 = QtWidgets.QWidget(parent=self.icon_text_widget)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 720, 241, 91))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.settings_1 = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.settings_1.setStyleSheet("QPushButton{\n"
"padding-left:-65px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color:white;\n"
"    borde-radius:3px;\n"
"}")
        self.settings_1.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/settings2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon7.addPixmap(QtGui.QPixmap(":/settings1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.settings_1.setIcon(icon7)
        self.settings_1.setIconSize(QtCore.QSize(100, 60))
        self.settings_1.setCheckable(True)
        self.settings_1.setObjectName("settings_1")
        self.verticalLayout_9.addWidget(self.settings_1)
        self.sign_out_1 = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.sign_out_1.setStyleSheet("QPushButton{\n"
"padding-left:-65px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color:white;\n"
"    borde-radius:3px;\n"
"}")
        self.sign_out_1.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/signout2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon8.addPixmap(QtGui.QPixmap(":/signout1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.sign_out_1.setIcon(icon8)
        self.sign_out_1.setIconSize(QtCore.QSize(100, 60))
        self.sign_out_1.setCheckable(True)
        self.sign_out_1.setObjectName("sign_out_1")
        self.verticalLayout_9.addWidget(self.sign_out_1)
        self.layoutWidget3 = QtWidgets.QWidget(parent=self.icon_text_widget)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 91, 241, 551))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.dashboard_2 = QtWidgets.QPushButton(parent=self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dashboard_2.setFont(font)
        self.dashboard_2.setStyleSheet("QPushButton{\n"
"padding-left:-60px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color:white;\n"
"    borde-radius:3px;\n"
"}")
        self.dashboard_2.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/dashboard2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon9.addPixmap(QtGui.QPixmap(":/dashboard1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.dashboard_2.setIcon(icon9)
        self.dashboard_2.setIconSize(QtCore.QSize(100, 60))
        self.dashboard_2.setCheckable(True)
        self.dashboard_2.setObjectName("dashboard_2")
        self.verticalLayout_10.addWidget(self.dashboard_2)
        self.institution_2 = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.institution_2.setStyleSheet("QPushButton{\n"
"padding-left:-65px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color:white;\n"
"    borde-radius:3px;\n"
"}")
        self.institution_2.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/institution2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon10.addPixmap(QtGui.QPixmap(":/institution1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.institution_2.setIcon(icon10)
        self.institution_2.setIconSize(QtCore.QSize(95, 45))
        self.institution_2.setCheckable(True)
        self.institution_2.setObjectName("institution_2")
        self.verticalLayout_10.addWidget(self.institution_2)
        self.students = QtWidgets.QFrame(parent=self.layoutWidget3)
        self.students.setEnabled(True)
        self.students.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.students.setObjectName("students")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.students)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.students_1 = QtWidgets.QPushButton(parent=self.students)
        self.students_1.setMinimumSize(QtCore.QSize(204, 69))
        self.students_1.setStyleSheet("QPushButton:checked{\n"
"\n"
"    borde-radius:3px;\n"
"}")
        self.students_1.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/students3.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon11.addPixmap(QtGui.QPixmap(":/students4.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.students_1.setIcon(icon11)
        self.students_1.setIconSize(QtCore.QSize(200, 60))
        self.students_1.setCheckable(True)
        self.students_1.setObjectName("students_1")
        self.verticalLayout_7.addWidget(self.students_1)
        self.students_dropdown = QtWidgets.QFrame(parent=self.students)
        self.students_dropdown.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.students_dropdown.setObjectName("students_dropdown")
        self.student_transactions = QtWidgets.QPushButton(parent=self.students_dropdown)
        self.student_transactions.setGeometry(QtCore.QRect(1, 61, 241, 28))
        self.student_transactions.setStyleSheet("QPushButton{\n"
"padding-left:50px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.student_transactions.setCheckable(True)
        self.student_transactions.setObjectName("student_transactions")
        self.student_payments = QtWidgets.QPushButton(parent=self.students_dropdown)
        self.student_payments.setGeometry(QtCore.QRect(0, 31, 241, 28))
        self.student_payments.setStyleSheet("QPushButton{\n"
"padding-left:35px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.student_payments.setCheckable(True)
        self.student_payments.setObjectName("student_payments")
        self.student_info = QtWidgets.QPushButton(parent=self.students_dropdown)
        self.student_info.setGeometry(QtCore.QRect(0, 1, 241, 28))
        self.student_info.setStyleSheet("QPushButton{\n"
"padding-left:45px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.student_info.setCheckable(True)
        self.student_info.setObjectName("student_info")
        self.verticalLayout_7.addWidget(self.students_dropdown)
        self.verticalLayout_10.addWidget(self.students)
        self.teachers = QtWidgets.QFrame(parent=self.layoutWidget3)
        self.teachers.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.teachers.setObjectName("teachers")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.teachers)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.teachers_1 = QtWidgets.QPushButton(parent=self.teachers)
        self.teachers_1.setMinimumSize(QtCore.QSize(204, 69))
        self.teachers_1.setStyleSheet("QPushButton:checked{\n"
"    \n"
"    borde-radius:3px;\n"
"}")
        self.teachers_1.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/teachers3.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon12.addPixmap(QtGui.QPixmap(":/teachers4.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.teachers_1.setIcon(icon12)
        self.teachers_1.setIconSize(QtCore.QSize(200, 60))
        self.teachers_1.setCheckable(True)
        self.teachers_1.setObjectName("teachers_1")
        self.verticalLayout_6.addWidget(self.teachers_1)
        self.teachers_dropdown = QtWidgets.QFrame(parent=self.teachers)
        self.teachers_dropdown.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.teachers_dropdown.setObjectName("teachers_dropdown")
        self.teacher_transactions = QtWidgets.QPushButton(parent=self.teachers_dropdown)
        self.teacher_transactions.setGeometry(QtCore.QRect(0, 60, 241, 28))
        self.teacher_transactions.setStyleSheet("QPushButton{\n"
"padding-left:28px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.teacher_transactions.setCheckable(True)
        self.teacher_transactions.setObjectName("teacher_transactions")
        self.teacher_salaries = QtWidgets.QPushButton(parent=self.teachers_dropdown)
        self.teacher_salaries.setGeometry(QtCore.QRect(0, 30, 241, 28))
        self.teacher_salaries.setStyleSheet("QPushButton{\n"
"padding-left:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.teacher_salaries.setCheckable(True)
        self.teacher_salaries.setObjectName("teacher_salaries")
        self.teacher_info = QtWidgets.QPushButton(parent=self.teachers_dropdown)
        self.teacher_info.setGeometry(QtCore.QRect(0, 0, 241, 28))
        self.teacher_info.setStyleSheet("QPushButton{\n"
"padding-left:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.teacher_info.setCheckable(True)
        self.teacher_info.setObjectName("teacher_info")
        self.verticalLayout_6.addWidget(self.teachers_dropdown)
        self.verticalLayout_10.addWidget(self.teachers)
        self.finances = QtWidgets.QFrame(parent=self.layoutWidget3)
        self.finances.setEnabled(True)
        self.finances.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.finances.setObjectName("finances")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.finances)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.finances_1 = QtWidgets.QPushButton(parent=self.finances)
        self.finances_1.setMinimumSize(QtCore.QSize(204, 69))
        self.finances_1.setStyleSheet("QPushButton:checked{\n"
"\n"
"    borde-radius:3px;\n"
"}")
        self.finances_1.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/finances3.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon13.addPixmap(QtGui.QPixmap(":/finances4.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.finances_1.setIcon(icon13)
        self.finances_1.setIconSize(QtCore.QSize(200, 100))
        self.finances_1.setCheckable(True)
        self.finances_1.setObjectName("finances_1")
        self.verticalLayout_8.addWidget(self.finances_1)
        self.finances_dropdown = QtWidgets.QFrame(parent=self.finances)
        self.finances_dropdown.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.finances_dropdown.setObjectName("finances_dropdown")
        self.budgets = QtWidgets.QPushButton(parent=self.finances_dropdown)
        self.budgets.setGeometry(QtCore.QRect(0, 0, 241, 28))
        self.budgets.setStyleSheet("QPushButton{\n"
"padding-left:-27px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.budgets.setCheckable(True)
        self.budgets.setObjectName("budgets")
        self.expenses = QtWidgets.QPushButton(parent=self.finances_dropdown)
        self.expenses.setGeometry(QtCore.QRect(0, 30, 241, 28))
        self.expenses.setStyleSheet("QPushButton{\n"
"padding-left:-19px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.expenses.setCheckable(True)
        self.expenses.setObjectName("expenses")
        self.business_overview = QtWidgets.QPushButton(parent=self.finances_dropdown)
        self.business_overview.setGeometry(QtCore.QRect(0, 60, 241, 28))
        self.business_overview.setStyleSheet("QPushButton{\n"
"padding-left:32px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#12B298\n"
"}")
        self.business_overview.setCheckable(True)
        self.business_overview.setObjectName("business_overview")
        self.verticalLayout_8.addWidget(self.finances_dropdown)
        self.verticalLayout_10.addWidget(self.finances)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.layoutWidget4 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layoutWidget5 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.layoutWidget6 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(340, 0, 867, 831))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.icon_only_widget = QtWidgets.QWidget(parent=self.layoutWidget6)
        self.icon_only_widget.setEnabled(True)
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.icon_only_widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.pushButton.setStyleSheet("border:none;")
        self.pushButton.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/menu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon14)
        self.pushButton.setIconSize(QtCore.QSize(29, 35))
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.icon_only_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_5 = QtWidgets.QLabel(parent=self.icon_only_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(72, 72, 72);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.icon_only_widget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 31))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"padding-left:20px;\n"
"border:1px solid gray;\n"
"border-radius:10px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label_6 = QtWidgets.QLabel(parent=self.icon_only_widget)
        self.label_6.setMaximumSize(QtCore.QSize(40, 40))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/profile.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.icon_only_widget)
        self.main_screen_widget = QtWidgets.QWidget(parent=self.layoutWidget6)
        self.main_screen_widget.setEnabled(True)
        self.main_screen_widget.setMinimumSize(QtCore.QSize(841, 741))
        self.main_screen_widget.setMaximumSize(QtCore.QSize(841, 741))
        self.main_screen_widget.setStyleSheet("")
        self.main_screen_widget.setObjectName("main_screen_widget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.main_screen_widget)
        self.stackedWidget.setGeometry(QtCore.QRect(9, 10, 232, 188))
        self.stackedWidget.setMaximumSize(QtCore.QSize(841, 741))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_7 = QtWidgets.QLabel(parent=self.page)
        self.label_7.setGeometry(QtCore.QRect(330, 210, 161, 141))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_8 = QtWidgets.QLabel(parent=self.page_2)
        self.label_8.setGeometry(QtCore.QRect(340, 200, 161, 141))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_9 = QtWidgets.QLabel(parent=self.page_3)
        self.label_9.setGeometry(QtCore.QRect(250, 210, 331, 141))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_10 = QtWidgets.QLabel(parent=self.page_4)
        self.label_10.setGeometry(QtCore.QRect(270, 200, 301, 141))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_11 = QtWidgets.QLabel(parent=self.page_5)
        self.label_11.setGeometry(QtCore.QRect(250, 200, 361, 141))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_12 = QtWidgets.QLabel(parent=self.page_6)
        self.label_12.setGeometry(QtCore.QRect(290, 230, 271, 141))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.label_13 = QtWidgets.QLabel(parent=self.page_7)
        self.label_13.setGeometry(QtCore.QRect(310, 200, 221, 141))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.label_14 = QtWidgets.QLabel(parent=self.page_8)
        self.label_14.setGeometry(QtCore.QRect(280, 210, 281, 141))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.stackedWidget.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.label_15 = QtWidgets.QLabel(parent=self.page_9)
        self.label_15.setGeometry(QtCore.QRect(350, 210, 181, 141))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.stackedWidget.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.label_16 = QtWidgets.QLabel(parent=self.page_10)
        self.label_16.setGeometry(QtCore.QRect(350, 210, 161, 141))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.stackedWidget.addWidget(self.page_10)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.label_17 = QtWidgets.QLabel(parent=self.page_11)
        self.label_17.setGeometry(QtCore.QRect(280, 190, 311, 141))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.stackedWidget.addWidget(self.page_11)
        self.verticalLayout_4.addWidget(self.main_screen_widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1212, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.students_1.toggled['bool'].connect(self.students_dropdown.setHidden) # type: ignore
        self.teachers_1.toggled['bool'].connect(self.teachers_dropdown.setHidden) # type: ignore
        self.finances_1.toggled['bool'].connect(self.finances_dropdown.setHidden) # type: ignore
        self.dashboard_2.toggled['bool'].connect(self.dashboard_1.setChecked) # type: ignore
        self.institution_2.toggled['bool'].connect(self.institution_1.setChecked) # type: ignore
        self.students_1.toggled['bool'].connect(self.students_2.setChecked) # type: ignore
        self.teachers_1.toggled['bool'].connect(self.teachers_2.setChecked) # type: ignore
        self.finances_1.toggled['bool'].connect(self.finances_2.setChecked) # type: ignore
        self.settings_1.toggled['bool'].connect(self.settings_2.setChecked) # type: ignore
        self.sign_out_1.toggled['bool'].connect(self.sign_out_2.setChecked) # type: ignore
        self.sign_out_2.toggled['bool'].connect(MainWindow.close) # type: ignore
        self.sign_out_1.toggled['bool'].connect(MainWindow.close) # type: ignore
        self.pushButton.toggled['bool'].connect(self.icon_text_widget.setHidden) # type: ignore
        self.pushButton.toggled['bool'].connect(self.widget.setVisible) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.student_transactions.setText(_translate("MainWindow", "Customer Transactions"))
        self.student_payments.setText(_translate("MainWindow", "Customer Payments"))
        self.student_info.setText(_translate("MainWindow", "Customer Information"))
        self.teacher_transactions.setText(_translate("MainWindow", "Staff Transactions"))
        self.teacher_salaries.setText(_translate("MainWindow", "Staff Salaries"))
        self.teacher_info.setText(_translate("MainWindow", "Staff Information"))
        self.budgets.setText(_translate("MainWindow", "Budgets"))
        self.expenses.setText(_translate("MainWindow", "Expenses"))
        self.business_overview.setText(_translate("MainWindow", "Business Overview"))
        self.label.setText(_translate("MainWindow", "Hello"))
        self.label_5.setText(_translate("MainWindow", "Welcome to your page"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search Here..."))
        self.label_7.setText(_translate("MainWindow", "Dashboard"))
        self.label_8.setText(_translate("MainWindow", "Institution"))
        self.label_9.setText(_translate("MainWindow", "Customer Information"))
        self.label_10.setText(_translate("MainWindow", "Customer Payments"))
        self.label_11.setText(_translate("MainWindow", "Customers Transactions"))
        self.label_12.setText(_translate("MainWindow", "Staff Information"))
        self.label_13.setText(_translate("MainWindow", "Staff Salaries"))
        self.label_14.setText(_translate("MainWindow", "Staff Transactions"))
        self.label_15.setText(_translate("MainWindow", "Budgets"))
        self.label_16.setText(_translate("MainWindow", "Expenses"))
        self.label_17.setText(_translate("MainWindow", "Bussiness Overview"))
